### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by kirus21** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-kirus21#2]
corregido

**Comment by kirus21** [comment]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-kirus21/files/9427409/Infografia.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACIÓN: 17/20

No se distingue bien la información, además falta imágenes y hay errores de ortografía.

**Comment by josealfredo79** [comment]
Hay que complementar las sugerencias...

**Comment by kirus21** [comment]
[Infografía Gestion de Proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-kirus21/files/9472414/Infografia.Gestion.de.Proyectos.pdf)
